project:
  type: book
  output-dir: ../_build/julia/skript

lang: de

book:
  title: "Julia und Jupyter Notebooks"
  subtitle: "Eine kurze Einführung für Anwendungen in der Numerik"
  author: "Matthias Baitsch"
  chapters:
    - index.qmd
    - 00-jupyter.qmd
    - 01-julia.qmd
    - 02-vektoren-und-matrizen.qmd
    - 03-plotten.qmd
    - 04-anfangswertprobleme.qmd
  downloads: 
    - pdf

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

