name: Build and deploy

on:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  render-and-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - name: Set up Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - name: Cache Julia packages
        uses: julia-actions/cache@v3
      - name: Install Julia packages
        run: julia --project=skript-julia -e 'using Pkg; Pkg.instantiate();'
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
      - name: Install Python packages
        run: uv sync --project skript-python
      - name: Install required command line tools
        run: sudo apt-get update && sudo apt-get install -y librsvg2-bin zip
      - name: Quarto render for Julia
        run: quarto render skript-julia
      - name: Quarto render for Python
        run: uv run --project skript-python quarto render skript-python
      - name: Prepare notebooks
        run: julia prepare-zipfile.jl julia python
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '_build'

  deploy:
    needs: render-and-zip
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v6
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
